## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)
# import gmaps.datasets

In [10]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(37)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Guerrero Negro,MX,71.96,clear sky,27.9769,-114.0611,NaN
1,6,Victoria,HK,72.03,overcast clouds,22.2855,114.1577,NaN
2,7,Sao Filipe,CV,78.58,overcast clouds,14.8961,-24.4956,NaN
3,9,Batang Berjuntai,MY,86.54,overcast clouds,3.3833,101.4167,NaN
4,10,Caucaia,BR,80.55,few clouds,-3.7361,-38.6531,NaN
5,18,Daru,PG,81.68,overcast clouds,-9.0763,143.2092,NaN
6,22,Buerarema,BR,77.59,clear sky,-14.9594,-39.2997,NaN
7,37,Isangel,VU,84.31,broken clouds,-19.5500,169.2667,NaN
8,40,Abnub,EG,70.02,clear sky,27.2696,31.1511,NaN
9,41,Santa Cruz Del Sur,CU,80.40,light rain,20.7147,-77.9956,NaN
10,42,Honiara,SB,86.95,few clouds,-9.4333,159.9500,NaN
11,46,Mandera,KE,77.22,overcast clouds,3.9366,41.8670,NaN
12,48,Buala,SB,84.56,light rain,-8.1450,159.5921,NaN
13,50,Butaritari,KI,81.88,scattered clouds,3.0707,172.7902,NaN
14,53,Malinyi,TZ,70.07,clear sky,-8.9333,36.1333,NaN
15,68,Mambatangan,PH,78.55,broken clouds,8.4333,124.8333,NaN
16,70,Napa,US,75.27,overcast clouds,38.4832,-122.3344,NaN
17,71,Kloulklubed,PW,84.70,overcast clouds,7.0419,134.2556,NaN
18,73,Coahuayana,MX,78.85,moderate rain,18.7333,-103.6833,NaN
19,74,Japura,ID,76.30,overcast clouds,-0.3167,102.3500,NaN
20,76,Hilo,US,89.28,scattered clouds,19.7297,-155.0900,NaN
21,81,Gamboma,CG,71.78,light rain,-1.8764,15.8644,NaN
22,82,Vaini,TO,84.36,scattered clouds,-21.2000,-175.2000,NaN
23,84,Port Augusta,AU,71.15,overcast clouds,-32.5000,137.7667,NaN
24,85,Cayenne,GF,77.04,few clouds,4.9333,-52.3333,NaN
25,86,Lompoc,US,73.54,clear sky,34.6391,-120.4579,NaN
26,90,Ponta Do Sol,PT,74.01,few clouds,32.6667,-17.1000,NaN
27,92,Atuona,PF,76.89,scattered clouds,-9.8000,-139.0333,NaN
28,94,Celestun,MX,80.73,light rain,20.8667,-90.4000,NaN
29,95,Palauig,PH,83.46,broken clouds,15.4350,119.9045,NaN
30,99,Airai,TL,73.22,broken clouds,-8.9266,125.4092,NaN
31,101,Nicoya,CR,74.39,overcast clouds,10.1483,-85.4520,NaN
32,103,Neiafu,TO,83.08,few clouds,-18.6500,-173.9833,NaN
33,104,Umm Lajj,SA,81.00,few clouds,25.0213,37.2685,NaN
34,107,Jimeta,NG,76.73,broken clouds,9.2833,12.4667,NaN
35,112,Kupang,ID,87.84,overcast clouds,-10.1667,123.5833,NaN
36,113,Acarau,BR,79.05,broken clouds,-2.8856,-40.1200,NaN

In [11]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country Code</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [12]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.8)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Lockhart"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Lockhart"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Harper"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Kupang"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Cayenne"]

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = tuple(vacation_start[["Lat","Lng"]].to_numpy()[0])
end = tuple(vacation_end[["Lat","Lng"]].to_numpy()[0])
stop1 = tuple(vacation_stop1[["Lat","Lng"]].to_numpy()[0])
stop2 = tuple(vacation_stop2[["Lat","Lng"]].to_numpy()[0])
stop3 = tuple(vacation_stop3[["Lat","Lng"]].to_numpy()[0])

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
vacation_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')

fig.add_layer(vacation_itinerary)
fig

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([],ignore_index=True)
itinerary_df

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map.

# 11b. Display the figure